"""remove unique from todo item field

Revision ID: f22b76dde394
Revises: ef2763efe1bf
Create Date: 2020-05-25 13:29:56.884149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22b76dde394'
down_revision = 'ef2763efe1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('text', table_name='item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('text', 'item', ['text'], unique=True)
    # ### end Alembic commands ###
