#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


export TODOS_DATABASE_URI="mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

mysql_ready() {
python << END
import sys
import MySQLdb
try:
    MySQLdb._mysql.connect(
        db="${DB_NAME}",
        user="${DB_USER}",
        passwd="${DB_PASSWORD}",
        host="${DB_HOST}",
        port=${DB_PORT},
    )
except MySQLdb._exceptions.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)
END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"